### ISSUE TITLE
La aplicación inicia en un View sin salida.

### ISSUE THREAD

**Issue by MartinCastellon** [mike2c/MyNotebook#1]
Al correr la aplicación por primera vez, me lleva a un View sin salida. Es decir, en el View no hay ninguna opción para hacer una acción, de las requeridas por el documento de requerimientos.  Todos los enlaces llevan a la misma View (Ver imagen adjunta). 

![image](https://user-images.githubusercontent.com/45889559/152697850-abd77628-e822-492f-961d-ac184f57eef7.png)

La aplicación debe de ser capaz de proporcionar la habilidad para realizar todas las historias de usuario, desde su primera ejecución. 

¿Como lo resolverias?

**Comment by mike2c** [comment]
Lo siento, olvide validar este escenario nuevamente luego de que agregue esta pantalla que se muestra cuando una búsqueda no arroja resultados. 

Este problema quedo corregido en el commit dc0ba8a19e7d49a1f9d597fc92849a059012e491 

![image](https://user-images.githubusercontent.com/8660882/152710059-2166e8d6-95ae-47b7-a079-8b76e4ca755f.png)

Gracias por reportar el problema.
